BEGIN {
  inheader=0;
  current_file="";
  if (headername=="") {
    headername="_PROTO_H_";
  }

  print "#ifndef",headername
  print "#define",headername
  print ""
  print "/* This file is automatically generated with \"make proto\". DO NOT EDIT */"
  print ""
}

END {
  print ""
  print "#endif /* ",headername," */"
}

{
  if (FILENAME!=current_file) {
    print ""
    print "/* The following definitions come from",FILENAME," */"
    print ""
    current_file=FILENAME
  }
  if (inheader) {
    if (match($0,"[)][ \t]*$")) {
      inheader = 0;
      printf "%s;\n",$0;
    } else {
      printf "%s\n",$0;
    }
    next;
  }
}

/^extern/ || !/^[a-zA-Z]/ || /[;]/ {
  next;	
}

#
# if there comes more start types, then split up the start matching because it may cause awk to choke and fail
#
{
  gotstart = 0;
  if( $0 ~ /^static|^const|^inline|^mempool|^link_mem_chunk|^link_mempool|^link_intra_mempool|^void|^unsigned|^int|^bool|^size_t|^off_t|^double/ ) {
    gotstart = 1;
  }

  if(!gotstart) {
    next;
  }
}

/[(].*[)][ \t]*$/ {
    printf "%s;\n",$0;
    next;
}

/[(]/ {
  inheader=1;
  printf "%s\n",$0;
  next;
}

